# Generated by Django 2.2.17 on 2021-03-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swiped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='滑动者的ID')),
                ('sid', models.IntegerField(verbose_name='被滑动者的ID')),
                ('stype', models.CharField(choices=[('like', '喜欢'), ('superlike', '超级喜欢'), ('dislike', '不喜欢')], max_length=10, verbose_name='滑动类型')),
                ('stime', models.DateField(auto_now_add=True, verbose_name='滑动时间')),
            ],
            options={
                'unique_together': {('uid', 'sid')},
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid1', models.IntegerField(verbose_name='UID1')),
                ('uid2', models.IntegerField(verbose_name='UID2')),
            ],
            options={
                'unique_together': {('uid1', 'uid2')},
            },
        ),
    ]
