# Generated by Django 2.2.17 on 2020-11-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201117_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dating_location',
            field=models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('深圳', '深圳'), ('郑州', '郑州'), ('西安', '西安'), ('成都', '成都'), ('沈阳', '沈阳')], default='北京', max_length=16, verbose_name='目标城市'),
        ),
    ]
