# Generated by Django 2.2.17 on 2021-03-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210317_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vip_expire',
            field=models.DateTimeField(default='3000-1-1', verbose_name='VIP的过期时间'),
        ),
    ]
